# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTry01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_try01(self):
    # Test name: try 01
    # Step # | name | target | value
    # 1 | open | /mjol | 
    self.driver.get("https://mol.hostplus.com.au/mjol")
    # 2 | setWindowSize | 1024x768 | 
    self.driver.set_window_size(1024, 768)
    # 3 | click | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name | 
    self.driver.find_element(By.ID, "mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name").click()
    # 4 | type | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name | JONATHON PAUL
    self.driver.find_element(By.ID, "mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name").send_keys("JONATHON PAUL")
    # 5 | click | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name | 
    self.driver.find_element(By.ID, "mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name").click()
    # 6 | type | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name | BRUSSOW
    self.driver.find_element(By.ID, "mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name").send_keys("BRUSSOW")
    # 7 | click | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth | 
    self.driver.find_element(By.ID, "mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth").click()
    # 8 | type | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth | 29-03-1966
    self.driver.find_element(By.ID, "mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth").send_keys("29-03-1966")
  
