// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('try 01', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('try 01', async function() {
    // Test name: try 01
    // Step # | name | target | value
    // 1 | open | /mjol | 
    await driver.get("https://mol.hostplus.com.au/mjol")
    // 2 | setWindowSize | 1024x768 | 
    await driver.manage().window().setRect({ width: 1024, height: 768 })
    // 3 | click | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name | 
    await driver.findElement(By.id("mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name")).click()
    // 4 | type | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name | JONATHON PAUL
    await driver.findElement(By.id("mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.first-name")).sendKeys("JONATHON PAUL")
    // 5 | click | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name | 
    await driver.findElement(By.id("mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name")).click()
    // 6 | type | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name | BRUSSOW
    await driver.findElement(By.id("mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-1.last-name")).sendKeys("BRUSSOW")
    // 7 | click | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth | 
    await driver.findElement(By.id("mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth")).click()
    // 8 | type | id=mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth | 29-03-1966
    await driver.findElement(By.id("mjol-form.personal-details.personal-details-input-wrapper.personal-details-sub-layout-line-2.date-of-birth")).sendKeys("29-03-1966")
  })
})
